### ISSUE TITLE
v2.4.0 client gets into modeless state when there are patient records present

### ISSUE THREAD

**Issue by martinburchell** [ucam-department-of-psychiatry/camcops#114]
There is a problem if you upgrade the client to v2.4.0 and there are patient records present in the old database.

To reproduce:
* Set up a patient on v2.3.8 client.
* Upgrade client to v2.4.0.

You don't get the mode selection dialogue and you get a warning dialogue saying "Can't change mode" (because the patient records are present). The client then ends up in a hybrid mode state.

Workarounds:
* Install the v2.3.8 client and ensure all records are uploaded and erased before upgrading. This should also allow you to change the user and server details if they are incorrect.
* With the v2.4.0 client, if the user and server details are correct, it should be possible to hit the upload button. When you restart the client you should then be able to change mode.
* Delete the SQLite database, either manually or through the forgotten password workflow 

The client ends up in a hybrid mode state because the code assumes the mode will be set on initialization. The clinician / single user mode checks do not consider MODE_NOT_SET.

@RudolfCardinal we could fix this by defaulting to clinician mode if the database exists already. What do you think?

**Comment by RudolfCardinal** [comment]
Hmm. Just checking for the existence of the database might create some other odd effects (e.g. start with a blank canvas, abort, restart -- would then go into clinician mode?). But there are the two hooks void CamcopsApp::upgradeDatabaseBeforeTablesMade() and void CamcopsApp::upgradeDatabaseAfterTasksRegistered(const Version& old_version), both called from void CamcopsApp::backgroundStartup().

One approach might be to say, in upgradeDatabaseAfterTasksRegistered(), that if the old_version is valid (will be invalid if "blank slate") but not the same as the current version, then go straight to clinician mode?

Or, in the same function, to say that if patient records are present but the mode isn't set, go to clinician mode? The latter more directly addresses the problem, I suppose.

(Or a composite [AND] of those two.)

**Comment by martinburchell** [comment]
Closing this as no one has reported it as a problem.
