### ISSUE TITLE
Upgrade to Qt 6.x

### ISSUE THREAD

**Issue by martinburchell** [ucam-department-of-psychiatry/camcops#173]
According to https://www.qt.io/blog/2018/12/06/qt-5-12-lts-released Qt 5.12 will reach EOL December 2021

According to https://www.qt.io/blog/qt-roadmap-for-2021 Qt 6.2 will be the next LTS release in September 2021. So maybe wait until then.

https://doc-snapshots.qt.io/qt6-dev/portingguide.html

**Comment by RudolfCardinal** [comment]
Yes, agree -- looks like 6.2 is the one in which they catch up on back libraries! Maybe 6.1 would work but e.g. WebView is referred to a bit in our code (an unused #ifdef so perhaps not critical!) and that is scheduled for 6.2.

**Comment by martinburchell** [comment]
v6.2.0 was released today https://github.com/qt/qtbase/releases/tag/v6.2.0

**Comment by RudolfCardinal** [comment]
Should also fix https://bugreports.qt.io/browse/QTBUG-58503

**Comment by martinburchell** [comment]
There's some work in progress on the qt6.2 branch

**Comment by martinburchell** [comment]
Current plan is to upgrade to Qt6.5 LTS
