### ISSUE TITLE
CHI-T task update

### ISSUE THREAD

**Issue by RudolfCardinal** [ucam-department-of-psychiatry/camcops#269]
Per correspondence from Konstantinos Ioannidis, Sam Chamberlain (e.g. 2023-02-03, 2023-02-13): CHI-T task update

This adds one item and (versus some earlier versions) removes a question about subjective impairment.

* a/w clarification re method (update/new/replace)
* cite new paper: https://pubmed.ncbi.nlm.nih.gov/36680457/
* a/w clarification re licensing

**Comment by martinburchell** [comment]
Sam says "I think Ok to remove the old one. "

and "CHIT license requests can be directed to me or Jon Grant. There is a reduced rate for academic usage. It is not open access."

**Comment by martinburchell** [comment]
@RudolfCardinal do you think it's OK if we drop the q16 column altogether and change the scoring without trying to maintain backwards compatibility? I'm pretty sure the only study to use this task was MOJO and they finished their data collection a long time ago.

**Comment by martinburchell** [comment]
Golam confirms that it is OK to remove q16.
