### ISSUE TITLE
lupdate, lconvert, lrelease missing from Qt6 local build?

### ISSUE THREAD

**Issue by RudolfCardinal** [ucam-department-of-psychiatry/camcops#327]
``lupdate``, ``lconvert``, ``lrelease`` (translation tools) formerly present in e.g. ``.../qt_linux_x86_64_install/bin/`` for the Qt5 local build, but missing for Qt6. Our problem or a Qt6 build bug? At least two of the tools are still current, e.g.
* https://doc.qt.io/qt-6/linguist-lupdate.html
* https://doc.qt.io/qt-6/linguist-lrelease.html

... though slightly less clear re ``lconvert``.

**Comment by martinburchell** [comment]
Well spotted!

Hopefully fixed in d3994e53f374a4ecfc7a5a4bc08c31afe3a0ca92. Not yet tested.

I've tried to make the Qt build as small as possible so any required Git submodules need to be specified explicitly  in the `build_qt.py` script.

**Comment by martinburchell** [comment]
Fixed on the qt6.5 branch
